//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderInterface.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInfoByProducts
    {
        public int ProductID { get; set; }
        public string PName { get; set; }
        public decimal Price { get; set; }
        public int OrderID { get; set; }
        public int ProductOrderID { get; set; }
    }
}
